AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  updatesearchindex:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: updatesearchindex/index.handler
      Runtime: nodejs12.x
      Description: ''
      MemorySize: 128
      Timeout: 15
      Environment:
        Variables:
          REGION: "us-east-1"
          DOMAIN: "search-livestream-no-105-test-pnhejzppwfyhvb6yx663kisyne.us-east-1.es.amazonaws.com"